# Generated by Django 3.0.5 on 2020-04-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200404_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='type_identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Type_identity'),
        ),
    ]
