# Generated by Django 2.2.11 on 2020-04-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200409_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='type_identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Type_identity'),
        ),
    ]
