# Generated by Django 3.0.1 on 2020-03-21 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=0, max_digits=8)),
                ('state', models.BooleanField()),
                ('City', models.CharField(max_length=30)),
                ('neighborhood', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=120)),
                ('length', models.DecimalField(decimal_places=2, max_digits=3)),
                ('antiquity', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('amount_rooms', models.IntegerField()),
                ('stract', models.IntegerField()),
                ('description', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Property_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Type_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('current_state', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_number', models.IntegerField()),
                ('observations', models.CharField(max_length=600)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='property.Property')),
                ('type_management', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='property.Type_management')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='property.Property_state'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='property.Property_type'),
        ),
    ]
