# Generated by Django 2.2.11 on 2020-04-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_remove_property_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='length',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
