# Generated by Django 2.2.11 on 2020-04-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20200409_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
