# Generated by Django 2.2.11 on 2020-04-28 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property_bathrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
    ]
