# Generated by Django 3.0.5 on 2020-04-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='City',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='property_management',
            name='current_state',
            field=models.BooleanField(),
        ),
    ]
