# Generated by Django 2.2.11 on 2020-04-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='urlimage',
            field=models.ImageField(null=True, upload_to='property/%Y/%m/%d'),
        ),
    ]
